[project]
name = "SupercomputeProgramming"
uuid = "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d"
authors = ["Amazon Rainforest AI Collective"]
version = "0.1.0"

[deps]
# Core Julia ecosystem
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

# Python interoperability
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

# HPC and parallel computing
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

# Quantum computing simulation
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
QuantumInformation = "3c0b384b-479c-5684-b2ef-9d7a46dd931e"

# Web3 and blockchain
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

# Graph and network analysis
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"

# Optimization and symbolic computing
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

# Database and storage
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"

# Documentation and visualization
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
julia = "1.10"
PythonCall = "0.9"
Flux = "0.14"
CUDA = "5"
Yao = "0.9"
JuMP = "1.0"
HTTP = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["Test", "BenchmarkTools"]
